### ISSUE TITLE
rss 订阅链接失效

### ISSUE THREAD

**Issue by Sciroccogti** [EnigmaHuang/enigmahuang.github.io#1]
https://enigmahuang.me/atom_feed.xml 似乎404了

另外，恭喜顺利毕业！（刚好我也今年毕业了）

**Comment by EnigmaHuang** [comment]
已将主页下方的 RSS Feed 链接修正为 https://enigmahuang.me/feed.xml .
谢谢，也恭喜你顺利毕业。
